### ISSUE TITLE
userid instead chatid

### ISSUE THREAD

**Issue by stefanocudini** [ariedro/smtp-faker#1]
there is possibility to indicate the user id instead of the chat id??? this is a bit complicated to obtain

**Comment by ariedro** [comment]
Hi, sorry but the [Telegram API](https://core.telegram.org/bots/api#sendphoto) only supports passing the `chatId` parameter to identify which user would be the receipient for the photo. So you would need to obtain that id somehow.

**Comment by ariedro** [comment]
I'm closing the issue but I can help you with your problem, perhaps you could try to do the following:
1. Send a message to your bot
2. Make a `GET` request to the [getUpdates endpoint](https://core.telegram.org/bots/api#getupdates), this could be as simply as accessing the url `https://api.telegram.org/bot[your-bot-token]/getUpdates`
3. In the payload you should see a `chatId` for where the message has been sent.

**Comment by stefanocudini** [comment]
> I'm closing the issue but I can help you with your problem, perhaps you could try to do the following:
> 
> 1. Send a message to your bot
> 2. Make a `GET` request to the [getUpdates endpoint](https://core.telegram.org/bots/api#getupdates), this could be as simply as accessing the url `https://api.telegram.org/bot[your-bot-token]/getUpdates`
> 3. In the payload you should see a `chatId` for where the message has been sent.

thanks i don't know very well the mechanisms of the telegram protocol

What you say makes sense, I think it's the only way too, right?

if I understand correctly a bot cannot directly contact a userid according to the telegram rules? therefore the bot can only access chats previously opened by users

**Comment by ariedro** [comment]
Yes, the only way for a user to receive a message from a bot is if he previously sent a message to it or if they were both in the same group, so it would have an associated `chatId` with that conversation.
